question_data = [
    {"text": "A slug's blood is green.", "answer": "True"},
    {"text": "The loudest animal is the African Elephant.", "answer": "False"},
    {"text": "Approximately one quarter of human bones are in the feet.", "answer": "True"},
    {"text": "The total surface area of a human lungs is the size of a football pitch.", "answer": "True"},
    {"text": "In West Virginia, USA, if you accidentally hit an animal with your car, "
             "you are free to take it home to eat.", "answer": "True"},
    {"text": "In London, UK, if you happen to die in the House of Parliament, you are entitled to a state funeral.",
     "answer": "False"},
    {"text": "It is illegal to pee in the Ocean in Portugal.", "answer": "True"},
    {"text": "You can lead a cow down stairs but not up stairs.", "answer": "False"},
    {"text": "Google was originally called 'Backrub'.", "answer": "True"},
    {"text": "Buzz Aldrin's mother's maiden name was 'Moon'.", "answer": "True"},
    {"text": "No piece of square dry paper can be folded in half more than 7 times.", "answer": "False"},
    {"text": "A few ounces of chocolate can to kill a small dog.", "answer": "True"}
]

question_politics = [{"type": "boolean", "difficulty": "easy", "category": "Politics",
                    "question": "Russia passed a law in 2013 which outlaws telling children that homosexuals exist.",
                    "correct_answer": "True", "incorrect_answers": ["False"]},
                   {"type": "boolean", "difficulty": "easy", "category": "Politics",
                    "question": "There was a satirical candidate named &quot;Deez Nuts&quot; running in the 2016 US presidential elections.",
                    "correct_answer": "True", "incorrect_answers": ["False"]},
                   {"type": "boolean", "difficulty": "easy", "category": "Politics",
                    "question": "The S in Harry S. Truman stands for &quot;Samuel&quot;.",
                    "correct_answer": "False", "incorrect_answers": ["True"]},
                   {"type": "boolean", "difficulty": "hard", "category": "Politics",
                    "question": "George Clinton, Vice President of the United States (1805-1812), is an ancestor of President Bill Clinton.",
                    "correct_answer": "False", "incorrect_answers": ["True"]},
                   {"type": "boolean", "difficulty": "hard", "category": "Politics",
                    "question": "Nazi Germany surrendered on Harry Truman&#039;s birthday while he was president.",
                    "correct_answer": "True", "incorrect_answers": ["False"]},
                   {"type": "boolean", "difficulty": "medium", "category": "Politics",
                    "question": "The State of Queensland, Australia voted NO to a referendum for daylight savings in 1992.",
                    "correct_answer": "True", "incorrect_answers": ["False"]},
                   {"type": "boolean", "difficulty": "medium", "category": "Politics",
                    "question": "Helen Clark was the 37th Prime Minister of Australia.",
                    "correct_answer": "False", "incorrect_answers": ["True"]},
                   {"type": "boolean", "difficulty": "easy", "category": "Politics",
                    "question": "Denmark has a monarch.", "correct_answer": "True",
                    "incorrect_answers": ["False"]},
                   {"type": "boolean", "difficulty": "easy", "category": "Politics",
                    "question": "The 2016 United States Presidential Election is the first time Hillary Clinton has run for President.",
                    "correct_answer": "False", "incorrect_answers": ["True"]},
                   {"type": "boolean", "difficulty": "easy", "category": "Politics",
                    "question": "One of Barack Obama&#039;s United States presidential campaign slogan&#039;s was &quot;Yes We Can&quot;.",
                    "correct_answer": "True", "incorrect_answers": ["False"]}
                   ]
